# Generated by Django 4.2.7 on 2023-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
