# Generated by Django 4.2.7 on 2023-12-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_is_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='selected_categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_team',
        ),
    ]
